<Button>
    background_normal: ''
    background_color: (60/255, 90/255, 70/255)

<Label>
    font_size: 32

<MyLayout>
    BoxLayout:
        orientation: "vertical"
        # horizontal vertical
        size: root.width, root.height
        spacing: 10
        padding: 10

        Label:
            text: "something"

        TextInput:  
            multiline: False

        Button:
            text:"Hee"
        Button:
            text:"Hee"
        Button:
            text:"Hee"


