
<MyLayout>
    BoxLayout:
        orientation: "vertical"
        # horizontal vertical
        size: root.width, root.height
        spacing: 20
        padding: 50

        Button:
            text:"Hee"

        Button:
            text:"Hee"
    
        Button:
            text:"Hee"
            #size_hint:(0.5, 0.5)
            pos_hint: {'center_x':0.5}
            size_hint:(None, None)
            width: 100
            height: 50
